name: Java Selenium TestNG on Windows with WebDriverManager (Scheduled)

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 2 * * *'  # Every day at 2:00 AM UTC

jobs:
  testng-tests:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-

    - name: Run Tests with Maven
      run: mvn clean test

    - name: Upload ExtentReports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: extent-reports
        path: test-output/
